{
 "title": "Data Pipeline Metrics",
 "tags": [
  "pipeline",
  "home"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Extractor Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Extractor success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"batch-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Extractor failed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"batch-error\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "batch-error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Extractor Duplicates",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "duplicate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Extractor failed Percentage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"batch-error\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Telemetry Extractor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "failed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "failed" ], "type": "alias" }
        ],
        [
         { "params": [ "duplicate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "duplicate" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Telemetry Extractor Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"consumer_lag\") AS \"lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") + sum(\"failed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
       ]
      }
     ]
    },
    {
     "title": "Valid Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"duplicate\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'DeDuplication' AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'TelemetryValidator' AND $timeFilter",
       "select": [
        [
         { "params": [ "failed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Events %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"failed\") / (sum(\"success\") + sum(\"failed\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Telemetry Validator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "failed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "failed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
       ]
      }
     ]
    },
    {
     "title": "Telemetry Validator Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deduplication Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"job_name\" = 'DeDuplication' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Duplicate Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"duplicate\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'DeDuplication' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Duplicate Events %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"duplicate\") / (sum(\"success\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "De Duplication",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") AS \"success\", sum(\"duplicate\") AS \"duplicate\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "duplicate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "duplicate" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeDuplication" }
       ]
      }
     ]
    },
    {
     "title": "De Duplication Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeDuplication" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Primary Route Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"primary-route-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "skipped" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
       ]
      }
     ]
    },
    {
     "title": "Secondary Route Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"secondary-route-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Telemetry Router",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "primary-route-success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "primary" ], "type": "alias" }
        ],
        [
         { "params": [ "secondary-route-success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "secondary" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
       ]
      }
     ]
    },
    {
     "title": "Telemetry Router Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Location Updater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location Updater Total",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Processed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"processed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "processed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Unprocessed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"unprocessed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "unprocessed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Unprocessed %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"unprocessed\") / (sum(\"success\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Cache Hit",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "cache_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Cache Miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "cache_miss" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Cache Empty Values",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "cache_empty_values" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Cache Miss %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT (sum(\"cache_miss\") + sum(\"cache_empty_values\")) / sum(\"processed\") * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Cache Hit - User Profile",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "user_cache_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Cache Hit - Declared Location",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "user_declared_location_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Cache Hit - IP Location",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"ip_location_hit\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ip_location_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Resolve Location by IP %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"ip_location_hit\") / (sum(\"ip_location_hit\") + sum(\"user_declared_location_hit\") + sum(\"user_cache_hit\"))* 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Processed/Unprocessed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "select": [
        [
         { "params": [ "processed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "processed" ], "type": "alias" }
        ],
        [
         { "params": [ "unprocessed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "unprocessed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"user_cache_hit\") AS \"user_profile\", sum(\"user_declared_location_hit\") AS \"user_declared\", sum(\"ip_location_hit\") AS \"ip_location\", sum(\"cache_miss\") AS \"empty\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "user_cache_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "user_profile" ], "type": "alias" }
        ],
        [
         { "params": [ "user_declared_location_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "user_declared" ], "type": "alias" }
        ],
        [
         { "params": [ "ip_location_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "ip_location" ], "type": "alias" }
        ],
        [
         { "params": [ "cache_miss" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "empty" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    },
    {
     "title": "Location Updater Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"consumer_lag\") AS \"lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "De-Normalization job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Denorm Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeNormalization" }
       ]
      }
     ]
    },
    {
     "title": "Denorm Skipped",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"skipped\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
       "select": [
        [
         { "params": [ "skipped" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeNormalization" }
       ]
      }
     ]
    },
    {
     "title": "Denorm Expired",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"expired_event\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
       "select": [
        [
         { "params": [ "expired_event" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeNormalization" }
       ]
      }
     ]
    },
    {
     "title": "De Normalization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") AS \"success\", sum(\"skipped\") AS \"skipped\", sum(\"expired_event\") AS \"expired\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "skipped" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "skipped" ], "type": "alias" }
        ],
        [
         { "params": [ "expired_event" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "expired" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeNormalization" }
       ]
      }
     ]
    },
    {
     "title": "De Normalization Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"consumer_lag\") AS \"lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DeNormalization" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Validator and Events Router Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Druid Validator Total",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") + sum(\"failed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Druid Validator Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Druid Validator Failures",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
       "select": [
        [
         { "params": [ "failed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Events %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"failed\") / (sum(\"success\") + sum(\"failed\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Druid Router Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Druid Router Duplicates",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"duplicate\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Duplicate Events %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"duplicate\") / (sum(\"success\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "error" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
       ]
      }
     ]
    },
    {
     "title": "Druid Validator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") AS \"success\", sum(\"failed\") AS \"failed\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "failed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "failed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Druid Validator Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"consumer_lag\") AS \"lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
       ]
      }
     ]
    },
    {
     "title": "Events Router",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"success\") AS \"success\", sum(\"duplicate\") AS \"duplicate\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "success" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "success" ], "type": "alias" }
        ],
        [
         { "params": [ "duplicate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "duplicate" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "EventsRouter" }
       ]
      }
     ]
    },
    {
     "title": "Event Router Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pipeline_metrics",
       "query": "SELECT sum(\"consumer_lag\") AS \"lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "consumer_lag" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "lag" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "job_name", "operator": "=", "value": "EventsRouter" }
       ]
      }
     ]
    }
   ]
  }
 ]
}