{
 "title": "Data Pipeline Current Lag Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Main Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Telemetry Extractor",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Location Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Denormalization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter ",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Druid Events Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter ",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "Events Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "EventsRouter" }
     ]
    }
   ]
  },
  { "title": "Updaters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Content Cache Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "ContentCacheUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Device Profile Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceProfileUpdater" }
     ]
    }
   ]
  },
  {
   "title": "User Cache Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "UserCacheUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Share Event Flattener",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "SHARE_EVENTS_FLATTENER" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Redacter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRedacter" }
     ]
    }
   ]
  }
 ]
}