{
 "title": "EP-Pipeline - ConsumerLag",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TelemetryExtractor Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "dev" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeDuplication" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouter Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRouter" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryLocationUpdater Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "DeviceProfileUpdater",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceProfileUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceProfileUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Denormalization Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "EventsRouter Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "EventsRouter" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "AssessmentAggregator",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "AssessmentAggregator" }
     ]
    }
   ]
  }
 ]
}