{
 "title": "Fluent Bit",
 "description": "Inspired by https://grafana.com/grafana/dashboards/7752",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fluent Bits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluent-bit.*\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Non-Ready Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Input Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Retries to {{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "errors/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total[1m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{ name }}"
    }
   ]
  }
 ]
}