{
 "title": "Host Details",
 "description": "A simple overview of the most important Docker metrics export by node-expoter on docker swarm mode. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time_seconds,instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total{instance=\"$server:9256\"}, groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance='$server:9100'} / count by (cluster, job, instance)(count by(cluster, job, instance, cpu)(node_cpu_seconds_total{instance='$server:9100'}))"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server:9100\"}[5m])) * 100 / count(node_cpu_seconds_total{mode=\"user\", instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\", instance=\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (rate(node_cpu_seconds_total{instance=~\"$server:9100\", mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\",instance=~\"$server:9100\"}[5m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo', instance=~\"$server:9100\"}[5m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:9100\"} - node_memory_MemFree_bytes{instance=~\"$server:9100\"} - node_memory_Cached_bytes{instance=~\"$server:9100\"} - node_memory_Buffers_bytes{instance=~\"$server:9100\"} - node_memory_Slab_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server:9100\"} + node_memory_Slab_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$server:9100\"} / node_memory_MemTotal_bytes{instance=~\"$server:9100\"}) * 100"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "io time"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$server:9100\"}[5m])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_sockstat_TCP_inuse{instance=\"$server:9100\"})",
     "legendFormat": "Number of Open Connections"
    }
   ]
  },
  {
   "title": "Free Filesystem Space (Lowest)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:9100\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "Disk usage pattern",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_filesystem_free_bytes{instance=~'$server:9100', mountpoint='/'}[5m])",
     "legendFormat": "{{device}} mounted to {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:9100\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\", instance=~\"$server:9256\"}[$interval])) by (groupname,instance)",
     "legendFormat": "{{instance}} | {{groupname}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\", instance=~\"$server:9256\"}",
     "legendFormat": "{{instance}} | {{groupname}}"
    }
   ]
  },
  {
   "title": "Process Page Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\", instance=~\"$server:9256\"}",
     "legendFormat": "{{instance}} | {{groupname}}"
    }
   ]
  },
  {
   "title": "Number of Processes In Group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"$processes\", instance=~\"$server:9256\"}) by (groupname,instance)",
     "legendFormat": "{{instance}} | {{groupname}}"
    }
   ]
  }
 ]
}