{
 "title": "KP Flink Jobs Metrics",
 "tags": [
  "KP",
  "Flink",
  "Metrics",
  "Knowledge Job"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Post Publish Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Batch Creation Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_count[$__range]))"
    }
   ]
  },
  {
   "title": "Batch Creation Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Batch Creation Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "DialCode Link Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_count[$__range]))"
    }
   ]
  },
  {
   "title": "DialCode Link Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "DialCode Link Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "QR Image Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_qr_image_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Shallow Copy Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_shallow_copy_count[$__range]))"
    }
   ]
  },
  {
   "title": "Post Publish Processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Post Publish Processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"post-publish-processor-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  {
   "title": "QuestionSet Publish",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Question Publish Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_count[$__range]))"
    }
   ]
  },
  {
   "title": "Question Publish Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Question Publish Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "QuestionSet Publish Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_count[$__range]))"
    }
   ]
  },
  {
   "title": "QuestionSet Publish Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "QuestionSet Publish Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "QuestionSet Publish",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count) + sum(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count) + sum(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "QuestionSet Publish",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"questionset-publish-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Search Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count[$__range])) +  sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count[$__range])) +  sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Composite Search Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Composite Search Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Composite Search Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dialcode Metrics Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dailcode Metrics Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dailcode Metrics Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dailcode External Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dailcode Externla Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Dailcode External Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Search Indexer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Search Indexer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"search-indexer-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Activity Aggregate Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Batch Enrolment Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_batch_enrolment_update_count[$__range]))"
    }
   ]
  },
  {
   "title": "Retired Collection Skip Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_retired_consumption_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 76 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_skipped_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 76 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_failed_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Processed Enrolment Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 76 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_processed_enrolment_count[$__range]))"
    }
   ]
  },
  {
   "title": "DB Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_update_count[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Miss",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_miss_count[$__range]))"
    }
   ]
  },
  {
   "title": "DB Read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 84 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_read_count[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 84 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_hit_count[$__range]))"
    }
   ]
  },
  {
   "title": "Activity Aggregate Updater",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_failed_events_count)",
     "legendFormat": "ActivityAggregateFailed"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_batch_enrolment_update_count)",
     "legendFormat": "BatchEnolmentUpdate"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_update_count)",
     "legendFormat": "DB Update"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_miss_count)",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_total_events_count)",
     "legendFormat": "Total Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_processed_enrolment_count)",
     "legendFormat": "Processed Enrolments"
    }
   ]
  },
  {
   "title": "ActivityAggUpdater lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"activity-aggregate-updater-taskmanager-prometheus\"})",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Video Stream Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_skipped_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_success_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_failed_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Retried Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_retry_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Video Stream Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_success_events_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_skipped_events_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_failed_events_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Video Stream Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"video-stream-generator-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Relation Cache Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_success_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Write",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_cache_write_count[$__range]))"
    }
   ]
  },
  {
   "title": "DB Read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_db_read_count[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 110 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_failed_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Relation Cache Updater",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_success_events_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_failed_events_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "RelationCache Updater lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"relation-cache-updater-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  }
 ]
}