{
 "title": "Flink Lag Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "query": "ntpprod" }
  ]
 },
 "panels": [
  { "title": "KP Flink Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "activity aggregate Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-activity-aggregate-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "program activity agreegator",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-program-activity-aggregate-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "collection-cert-pre-processor Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-collection-cert-pre-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "program cert pre-processor",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-program-cert-pre-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "certificate generator Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-certificate-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "content publish Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-content-publish-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "questionset publish Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-questionset-publish-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "post publish processor Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-post-publish-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "search indexer Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-search-indexer-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "relation cache updater Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-relation-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "asset enrichment lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 1M\nCritical:  2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-asset-enrichment-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "audit history indexer Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-audit-history-indexer-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "audit event generator lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-audit-event-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "common certificate generator Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-common-certificate-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Karma Points Processor",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-karma-points-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "event certificate generator Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-event-certificate-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  { "title": "DP Flink Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Ingestion Router lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-telemetry-extractor-group\", job=\"processing-kafka-exporter\", topic=\"prod.telemetry.ingest\"})"
    }
   ]
  },
  {
   "title": "Telemetry Extractor lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-telemetry-extractor-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "PreProcessor lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-pipeline-preprocessor-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DenormalizationPrimary lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-telemetry-denorm-primary-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DenormalizationSecondary lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-telemetry-denorm-secondary-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "SummaryDenorm lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-summmary-denorm-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DruidValidator lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-druid-validator-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "UserCacheUpdaterV2 lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-user-cache-updater-consumer-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Rating lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-rating-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Error Denorm lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-error-denorm-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "ContentCacheUpdater lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"prod-content-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  { "title": "Secor Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "raw-telemetry-backup",
   "type": "graph",
   "description": "Threshold: \nWarning: 10M\nCritical: 15M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.raw.backup\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "failed-telemetry-backup",
   "type": "graph",
   "description": "Threshold: \nWarning: 15M\nCritical: 20M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.failed.backup\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "unique-telemetry-backup",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.unique.backup\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": " learning-events-backup",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.learning.graph.events.backup\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "issue-certificate-events-backup",
   "type": "graph",
   "description": "Threshold: \nWarning: 4M\nCritical: 8M",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.issue.certificate.request.backup\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "error-telemetry-backup",
   "type": "singlestat",
   "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 109 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.druid.events.error.backup\", job=\"processing-kafka-exporter\"}"
    }
   ]
  },
  {
   "title": "assess-raw-events-backup",
   "type": "singlestat",
   "description": "Threshold: \nWarning: 15M\nCritical: 20M",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 112 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.telemetry.assess.raw\", job=\"processing-kafka-exporter\"}"
    }
   ]
  },
  {
   "title": "WFS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Data Products time taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dataproduct_workflowsummarymodel_time_taken_secs)",
       "legendFormat": "time_taken: {{ subsystem }}"
      }
     ]
    },
    {
     "title": "Total Data Products Input count",
     "type": "table",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_input_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    },
    {
     "title": "Total Data Products Output count",
     "type": "table",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_output_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster DataSource Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary-Events",
     "type": "singlestat",
     "description": "DataSource name: summary-events",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Datasource name: telemetry-events-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Datasource name:  telemetry-feedback-events",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster Segment Unavailable Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContentModelSnapshot",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"content-model-snapshot\"}"
      }
     ]
    },
    {
     "title": "OfflineDesktopEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"offline-desktop-events\"}"
      }
     ]
    },
    {
     "title": "PipelineMetrics",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"pipeline-metrics\"}"
      }
     ]
    },
    {
     "title": "SummaryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryErrorEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-error-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Secor Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "learning-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-events-.+\"})"
      }
     ]
    },
    {
     "title": "derived-denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"derived-denorm-events-.+\"})"
      }
     ]
    },
    {
     "title": "channel-summary-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-summary-.+\"})"
      }
     ]
    },
    {
     "title": "assess-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-events-.+\"})"
      }
     ]
    },
    {
     "title": "assess-raw-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-raw-events-.+\"})"
      }
     ]
    },
    {
     "title": "device-profile-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"device-profile-.+\"})"
      }
     ]
    },
    {
     "title": "channel-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "learning-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-failed-.+\"})"
      }
     ]
    },
    {
     "title": "content-consumption-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"content-consumption-events-.+\"})"
      }
     ]
    },
    {
     "title": "failed-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"failed-telemetry-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-duplicate-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-duplicate-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-failed-.+\"})"
      }
     ]
    },
    {
     "title": "raw-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"raw-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "ingestion-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 4",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"ingestion-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"denorm-events-backup-.+\"})"
      }
     ]
    },
    {
     "title": "unique-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"unique-telemetry-backup-.+\"})"
      }
     ]
    }
   ]
  }
 ]
}