{
 "title": "Master Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(node_load1,cluster)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(container_last_seen, container_label_com_docker_swarm_service_name)"
   },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   }
  ]
 },
 "panels": [
  { "title": "Pipeline Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Publish Pipeline Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search indexer Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Peak of Request per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Daily Peaks of Request per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Max % HTTP 4xx Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Max % HTTP 4xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Max % HTTP 5xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..|4..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "API Requests Error %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", api=~\"${api}\",status!~\"2..|3..|5..\"}[5m])) by (api, status) / ignoring(api, status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", api=~\"${api}\"}[5m]))) by(api,status)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(kong_request_status_count{cluster=~\"$cluster\", api=~\"${api}\",status_code!~\"2..|3..|4..\"}[5m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count{cluster=~\"$cluster\", api=~\"${api}\"}[5m]))) by(api,status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  { "title": "Load Avg on VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Load avg on VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Container CPU Details - DS 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Container CPU Usage - DS1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{image!=\"\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage - DS 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{image!=\"\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Top 10 API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Top 10 API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{cluster=~\"$cluster\", api=~\"${api}\"}[5m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "APIs Avg/Min/Max Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "APIs Average/Min/Max Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kong_latency_time{cluster=~\"$cluster\", api=~\"${api}\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}