{
 "title": "NGINX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(nginx_http_requests_total, sb_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cache_status!~\"MISS|NONE\"}[5m]))",
     "legendFormat": "Cached Response"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m])) - sum(rate(nginx_http_requests_total{cache_status!~\"MISS|NONE\"}[5m]))",
     "legendFormat": "Not Cached Response"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{ status=\"444\"}[5m]))",
     "legendFormat": "Blocked Requests outside india"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"4..|5..\"}[5m])) by (status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}} {{ cache_status }}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..\"}[5m])) by (status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}