{
 "title": "Prometheus Stats",
 "description": "VIew Prometheus internal metrics: an extension of the standard dashboard.  Useful for tuning, probably overkill for daily use.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Local Storage Memory Series",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_memory_series"
    }
   ]
  },
  {
   "title": "Interal Storage Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_indexing_queue_length"
    }
   ]
  },
  {
   "title": "Checkpoint duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "prometheus_local_storage_checkpoint_last_duration_seconds"
    }
   ]
  },
  { "title": "Scrapes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Target Scrapes (last 5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  { "title": "Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_evaluator_duration_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Samples ingested (rate:5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_ingested_samples_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Persistence Urgency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_local_storage_persistence_urgency_score"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rushed mode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_local_storage_rushed_mode"
    }
   ]
  },
  {
   "title": "Chunks to persist",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_local_storage_chunks_to_persist"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Chunk ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_chunk_ops_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Series ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_series_ops_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}