{
 "title": "Weekly Report Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "ntpprod" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(container_last_seen, container_label_com_docker_swarm_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily Peak of Request per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Daily Peaks of Request per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Max % HTTP 4xx Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Max % HTTP 4xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max % HTTP 5xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "API Requests Error %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(kong_request_status_count{status_code!~\"2..|3..|5..\"}[5m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count[5m])))",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(kong_request_status_count{status_code!~\"2..|3..|4..\"}[5m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count[5m])))",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  { "title": "Load Avg on VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Load avg on VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load Avg of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{image!=\"\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Top 10 API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top 10 API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(kong_request_count[5m])",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "APIs Avg/Min/Max Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "APIs Average/Min/Max Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kong_latency_time", "legendFormat": "{{api}}" }
   ]
  },
  { "title": "Publish Pipeline Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Publish Pipeline Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "publish-pipeline" }
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "publish-pipeline" }
     ]
    }
   ]
  },
  { "title": "Composite Indexer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Composite Indexer Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "composite-search-indexer" }
     ]
    }
   ]
  },
  {
   "title": "Composite Indexer Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"error\", \"failed\" FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/ AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "composite-search-indexer" }
     ]
    }
   ]
  },
  { "title": "Telemetry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Telemetry Validator Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"pipeline_metrics\" WHERE \"env\" = 'ntpprod' AND \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  }
 ]
}